foreground   #aad9e0
background   #0b090d
cursor       #aad9e0

color0       #0b090d
color8       #76979c
color1       #D5682D
color9       #D5682D
color2       #9E585A
color10      #9E585A
color3       #CC7255
color11      #CC7255
color4       #EB843B
color12      #EB843B
color5       #E78E5F
color13      #E78E5F
color6       #946D8B
color14      #946D8B
color7       #aad9e0
color15      #aad9e0
