foreground   #f3e7d6
background   #181236
cursor       #f3e7d6

color0       #181236
color8       #aaa195
color1       #E77B9F
color9       #E77B9F
color2       #CF72A2
color10      #CF72A2
color3       #5091CB
color11      #5091CB
color4       #F38FA4
color12      #F38FA4
color5       #F7A3A9
color13      #F7A3A9
color6       #FACEB7
color14      #FACEB7
color7       #f3e7d6
color15      #f3e7d6
