local telescope = require("telescope.builtin")
local set = vim.keymap.set

set("n", "<leader>ff", telescope.find_files, { desc = "Telescope find files" })
set("n", "<leader>fg", telescope.live_grep, { desc = "Telescope live grep" })
set("n", "<leader>fb", telescope.buffers, { desc = "Telescope buffers" })
set("n", "<leader>fh", telescope.help_tags, { desc = "Telescope help tags" })
set("n", "L", "<Cmd>BufferNext<CR>", { desc = "Move to next buffer" })
set("n", "H", "<Cmd>BufferPrevious<CR>", { desc = "Move to previous buffer" })
set("n", "<leader>bd", "<Cmd>BufferClose<CR>", { desc = "Close current buffer" })
set("n", "<leader>od", vim.diagnostic.open_float, { desc = "Open error message" })
set("n", "gd", vim.lsp.buf.definition, { desc = "Go to definition" })
set({ "n", "v" }, "<leader>ca", vim.lsp.buf.code_action, { desc = "Code actions" })
set("n", "<leader>e", "<Cmd>lua Snacks.explorer()<CR>", { desc = "Open file explorer" })
set("n", "<leader>wv", "<Cmd>vs<CR>", { desc = "Split window virtically" })
set("n", "<leader>ws", "<Cmd>sp<CR>", { desc = "Split window horizontally" })
set("n", "<C-h>", "<C-w>h", {})
set("n", "<C-j>", "<C-w>j", {})
set("n", "<C-k>", "<C-w>k", {})
set("n", "<C-l>", "<C-w>l", {})
set("n", "<leader>wd", "<C-w>q", {})
set("n", "<ESC>", "<Cmd>noh<CR>", {})
set({ "n", "v" }, "<leader>sy", '"+y', {})
set({ "n", "v" }, "<leader>sp", '"+p', {})
